### DISCUSSION TITLE
Hide temporary search engine / 隐藏临时搜索引擎

### DISCUSSION THREAD

**Discussion by nexmoe** [xiaoshuapp/effector#10] [Show and tell]
```css
/* Hide temporary search engine / 隐藏临时搜索引擎 */
#searchQuickEngine{
    display: none;
}
```
