### DISCUSSION TITLE
动态壁纸（含一些基础设置：滚动条，目录，工具栏之类的）

### DISCUSSION THREAD

**Discussion by Glace-Dev** [xiaoshuapp/effector#19] [General]
```css
html{
overflow: hidden;
}
.search {
z-index:1;
margin-bottom:50px !important;
}
.toolbar {
display:none !important;
}
#catalog {
display:none;
}
body{
width:100vw;
height:100vh;
}
element.style,
.v-application{
background-image:url("https://fastly.jsdelivr.net/gh/PuppetRuler/drawing-board@main/images/1706270874282preview.gif") !important;
}
```
