### DISCUSSION TITLE
透明主题修改版（含预览）

### DISCUSSION THREAD

**Discussion by uiliugang** [xiaoshuapp/effector#20] [Show and tell]
**效果预览**

![image](https://github.com/xiaoshuapp/effector/assets/74343774/9aa60172-ce3d-441f-a790-e31fe4a254cf)

**CSS 代码如下：** 
```css

/* 隐藏快速文件夹, 侧边栏 */
#catalog{display: none;}

/* 调整搜索框大小 */
.search {
 padding-top: 24px;
}
.col[data-v-90419595] {
	height: 50px;
}
.pill[data-v-90419595] {
    border-radius: 16px !important;
    height: 50px;
}
.v-field--center-affix .v-label.v-field-label{
	top:40%;
}
.v-field--center-affix .v-field__prepend-inner{
	height: 46px;
}
#chainwon-search[data-v-90419595] .v-input__append .v-icon{
	padding: 8px 22px 18px 18px;
}

.v-text-field .v-field--single-line input{
padding-top:2px;
}

/*  调整搜索框输入时的高度 */
#chainwon-search[data-v-90419595] .v-field__clearable {
	margin-top: 12px;
}

div[data-v-90419595].v-input--horizontal {
	height: 50px;
}

/*  删除联想词汇 */
.suggest {
	display:none;
}

/*搜索框居中*/
div[data-v-90419595] .v-row 
 {
    display: flex;
    flex-wrap: wrap;
    flex: 1 1 auto;
    margin: -12px;
    flex-direction: column;
    align-content: center;
}

/* 收藏按钮居中 */
.toolbar[data-v-7043ae68] {
    padding-top: 15px;
    margin-top: 2.5rem;
    margin-bottom: 1.5rem;
    margin-left: 1.25rem;
    display: flex;
    flex-direction: row;
    justify-content: center;
}

/* 隐藏 banner */
#banner {
display:none;
}

/* 搜索引擎选项卡*/
.v-col-4{
flex: 0 0 100%;
max-width: 615px;
}
.pa-2{
 margin-left: -25px;
 max-width: 585px;
}

/*隐藏 deleted  favorites */
.v-item-group .v-btn:nth-last-child(1) {
 display: none;
}

/*隐藏 workspace  favorites */
.v-item-group .v-btn:nth-last-child(2) {
 display: none;
}

/* 其他 */
.v-container {
    max-width: 1440px;
}
```
**插件设置**
![image](https://github.com/xiaoshuapp/effector/assets/74343774/19c7f839-9036-476f-ac59-d8083d916f85)

还有一些设置需要在 新标签页， 右键手动修改：两列显示，不显示图标。
