### DISCUSSION TITLE
自用毛玻璃主题

### DISCUSSION THREAD

**Discussion by zryyyy** [xiaoshuapp/effector#23] [Show and tell]
### 特性
- 毛玻璃
- 隐藏滚动条
- 优化搜索框
- 删除插件无法访问的⌈已删除收藏夹⌋

### 效果预览
![截图](https://github.com/xiaoshuapp/effector/assets/37234999/6281bed5-ecc9-4092-ad19-056f3397966d)

### css 代码

```css
/* 隐藏浏览器滚动条*/
::-webkit-scrollbar {
  display: none;
}

/* 毛玻璃效果 */
:root {
    --shu-card-background-color: rgba(200, 200, 200, 0.8);
}
.v-theme--light {
    --shu-card-background-color: rgba(255, 255, 255, 0.8);
}
.v-theme--dark {
    --shu-card-background-color: rgba(50, 50, 50, 0.7);
}
.shu-card {
    background-color: var(--shu-card-background-color, rgba(255, 255, 255, 0.8));
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
}

/* 隐藏插件无法访问的已删除收藏夹 */
.v-item-group button:last-child {
    display: none;
}


/* 将搜索框 position 属性从 relative 改为sticky */
.search {
    position: sticky !important;
    top: 24px;
}
.scrollY-banner .search {
    position: sticky !important;
    top: 24px;
}
```
