### DISCUSSION TITLE
自用 极简 毛玻璃主题 (只保留icon元素)

### DISCUSSION THREAD

**Discussion by liyinred** [xiaoshuapp/effector#24] [Show and tell]
![Weixin Screenshot_20241210193215](https://github.com/user-attachments/assets/bad263f2-e0b5-400e-85ef-2d7d76f482f1)

```css
body {
  --card-background-color: #ffffff90;
}

.flow .flow-header,
#banner,
.toolbar,
.search {
  display: none !important;
}

.flow {
  z-index: 0;
  margin-top: 0%;
  margin-bottom: -4%;
}

.shu-card {
  backdrop-filter: blur(15px);
}

::-webkit-scrollbar {
  display: none;
}

body {
  scrollbar-width: none;
}
```
