### DISCUSSION TITLE
Hide Scrollbar / 隐藏滚动条

### DISCUSSION THREAD

**Discussion by nexmoe** [xiaoshuapp/effector#7] [Show and tell]
```css
/* Hide Scrollbar / 隐藏滚动条 */
::-webkit-scrollbar {
	display: none;
}
body {
	scrollbar-width: none;
}
```
