### DISCUSSION TITLE
隐藏文件夹标题

### DISCUSSION THREAD

**Discussion by nexmoe** [xiaoshuapp/effector#8] [Show and tell]
```css
/* 隐藏文件夹标题 */
.flow .flow-header {
    display: none;
}
```
